(source gnu)
(source melpa)
(source marmalade)
(depends-on "flycheck")

;; modes
(depends-on "dockerfile-mode")
(depends-on "gitconfig-mode")
(depends-on "gitignore-mode")
(depends-on "groovy-mode")
(depends-on "markdown-mode")
(depends-on "ruby-mode")
(depends-on "yaml-mode")